# Fichier de configuration du site
### Configuration minimale
site_name: Documents du Loup
site_url: https://infoloup.myqnapcloud.com:8218/notes-du-loup/

### Configuration du dépôt
# Ajoute en haut à droite de chaque page du site, icône, nom et lien vers le dépot GitHub du projet.

### Configuration des métadonnées
site_description: Notes techniques du Loup
site_author: "Gérard Leloup"

### Configuration de la stucture de navigation
# Dossier source, chemin relatif au fichier mkdocs.yml
docs_dir: docs
# Structure du menu principal de navigation, chemins relatifs au dossier docs_dir
nav: 
  - Accueil : index.md
  - Informatique : 
    - Debian : 
      - informatique/debian/infos-materiel-hardinfo.md
    - Synology :
      - informatique/synology/docker-maj-de-nextcloud.md
  - MkDocs : 
    - mkdocs/bases-mkdocs.md
    - mkdocs/debian-mkdocs.md
    - mkdocs/github-mkdocs.md
  - WP Réseau Virtuel :
    - Pages :
      - wp-reseau-virtuel/pages/nouveautes-du-reseau-virtuel-2018.md
      - wp-reseau-virtuel/pages/prerequis.md
      - wp-reseau-virtuel/pages/elements-reseau-virtuel.md
      - wp-reseau-virtuel/pages/construction-reseau-virtuel-debian.md
    - Articles :
      - Hyperviseur VirtualBox :
        - wp-reseau-virtuel/articles/virtualbox-installation.md
        - wp-reseau-virtuel/articles/virtualbox-pont-reseau.md
      - Srv LAN Debian "srvlan" :
        - wp-reseau-virtuel/articles/serveur-debian12-srvlan-creation.md
      - Srv WAN IPFire "srvsec" :
        - wp-reseau-virtuel/articles/serveur-ipfire-srvsec-creation.md
      - Srv DMZ Debian "srvdmz" :
        - wp-reseau-virtuel/articles/serveur-debian12-srvdmz-creation.md
      - Cli LAN Debian "vm1 et 2" :
        - wp-reseau-virtuel/articles/clients-debian12-vm1-vm2-creation.md
      - Open vSwitch + Conteneurs :
        - wp-reseau-virtuel/articles/openvswitch-debian12-ovs-creation.md
        - wp-reseau-virtuel/articles/podman-debian12-lxc-partie-1.md
  # Référencer vos autres pages ci-dessus...

### Configuration du thème
theme:
  name: material
  language: fr    

### Palettes de couleurs jour/nuit
  #palette:
#### Configuration du comportement de la navigation
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
copyright: Copyright &copy; 2023 - Leloup G&eacute;rard

### Configuration des extensions MarkDown :
markdown_extensions:
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list # Ex Attribut image { align=left }
  - md_in_html
  - tables
  - fenced_code

### Gestion des styles
extra_css:
  - stylesheets/extra.css

### Gestion des plugins du site
plugins:
  - glightbox:
      touchNavigation: false
      loop: false
      effect: zoom
      slide_effect: slide
      width: 60%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom

