# Fichier de configuration du site
### Configuration minimale
site_name: Documents du Loup
site_url: https://loup79.github.io/notes-du-loup/

### Configuration du dépôt
# Ajoute en haut à droite de chaque page du site, icône, nom et lien vers le dépot GitHub du projet.
repo_url: https://github.com/loup79/notes-du-loup
repo_name: 'Dépot du Loup'
edit_uri: edit/main/docs/

### Configuration des métadonnées
site_description: Notes techniques du Loup
site_author: "Gérard Leloup"

### Configuration de la stucture de navigation
# Dossier source, chemin relatif au fichier mkdocs.yml
docs_dir: docs
# Structure du menu principal de navigation, chemins relatifs au dossier docs_dir
nav: 
  - Accueil :
    - index.md
    - page-prerequis.md
    - page-elements-reseau-virtuel.md
    - page-construction-reseau-virtuel-debian.md
    - page-liste-des-mementos.md
  - Réseau virtuel:
    - blog/index.md
  - Doc technique :
    - informatique/index.md 
    - Debian : 
      - informatique/debian/infos-materiel-hardinfo.md
      - informatique/debian/exim4-smarthost.md
    - Synology :
      - informatique/synology/docker-maj-de-nextcloud.md
  - Notes MkDocs :
    - mkdocs/index.md 
    - mkdocs/bases-mkdocs.md
    - mkdocs/debian-mkdocs.md
    - mkdocs/github-mkdocs.md  
  # Fin de la navigation

### Configuration du thème
theme:
  name: material
  language: fr
  logo: logo.png

# Comportement de la navigation
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer

  icon:
    repo: fontawesome/brands/github

copyright: Copyright &copy; 2023 - Leloup G&eacute;rard

### Configuration des extensions MarkDown :
markdown_extensions:
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - attr_list # Ex Attribut image { align=left }
  - md_in_html
  - tables
  - fenced_code

### Gestion des styles
extra_css:
  - stylesheets/extra.css

### Gestion des plugins du site
plugins:
  - blog:
      blog_dir: blog
      post_date_format: short
      post_url_format: "/{slug}"
      categories_url_format: "{slug}"
      archive: false
  - search :
      lang: fr
  - glightbox:
      touchNavigation: false
      loop: false
      effect: zoom
      slide_effect: none
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      skip_classes:
        - custom-skip-class-name
      auto_caption: true
      caption_position: bottom

